apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fenrus
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
spec:
  releaseName: fenrus
  chart:
    spec:
      chart: fenrus
      version: "1.0.0" # Replace with the desired chart version
      sourceRef:
        kind: GitRepository
        name: fenrus
        namespace: flux-system # Replace with the namespace where your GitRepository is located
  values:
    # Add any specific values for the Helm chart here
    env:
      - name: TZ
        value: America/New_York
    replicaCount: 1
    containers:
      - name: fenrus
        image: revenz/fenrus
        ports:
          - containerPort: 3000
        resources: {}
        volumeMounts:
          - mountPath: /app/data
            name: fenrus-claim0
    volumes:
      - name: fenrus-claim0
        persistentVolumeClaim:
          claimName: fenrus-claim0
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "{{ .Release.Name }}.${SECRET_DOMAIN}"
  interval: 5m # Adjust as per your preference
  timeout: 5m # Adjust as per your preference
