apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: fenrus-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/fenrus-default: "true"
            annotations:
              external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
  podSelector:
    matchLabels:
      io.kompose.network/fenrus-default: "true"
