apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
    external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
  creationTimestamp: null
  labels:
    io.kompose.service: fenrus
  name: fenrus
spec:
  replicas: 1
  service:
    main:
      ports:
        http:
          port: &port 8080
  selector:
    matchLabels:
      io.kompose.service: fenrus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/fenrus-default: "true"
        io.kompose.service: fenrus
    spec:
      containers:
        - env:
            - name: TZ
              value: America/New_York
          image: revenz/fenrus
          name: fenrus
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: fenrus-claim0
      restartPolicy: Always
      volumes:
        - name: fenrus-claim0
          persistentVolumeClaim:
            claimName: fenrus-claim0
status: {}
