---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fenrus
  namespace: default
spec:
  interval: 15m
  releaseName: my-fenrus
  chart:
    spec:
      chart: my-fenrus
      version: 2.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: tccr.io/truecharts/fenrus
      tag: latest
    service:
      main:
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
