---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: my-fenrus
      version: 2.0.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      pullPolicy: IfNotPresent
      repository: tccr.io/truecharts/fenrus
      tag: latest@sha256:4ed64c6bf51aeb4a571eebf362ec3125e80a6a2cd7cbdf843fe24d0bd136d264
    persistence:
      data:
        enabled: true
        mountPath: /app/data
      images:
        enabled: true
        mountPath: /app/wwwroot/images
    podSecurityContext:
      runAsGroup: 0
      runAsUser: 0
    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    service:
      main:
        ports:
          main:
            port: 3000
            protocol: TCP
            targetPort: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
