---
apiVersion: v1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-0
  namespace: database
  labels:
    app.kubernetes.io/name: redis
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
