kind: ENC[AES256_GCM,data:aldEEaFF,iv:1313HwAu0G/lCe/EzHflBvcpb8EvYB7VqySwy3qDp3s=,tag:pBOfUs84wW8Pebgdxxxf6w==,type:str]
ansible_user: ENC[AES256_GCM,data:ibAy2MMf,iv:NN/SRvKTeMSFpTiXJJTT2s5YYf/sib7IF9pbz1bB6dM=,tag:f2bv/CaYBQr1TWNftSu1qA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:K7BIbziLmoF1iuRa,iv:DlTru/H3Fi/uTmOjLGlw2sDDVxuq48gY4Y6WRkT4ef4=,tag:0LiJ13TjY6gY14CSCBkQmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u467mxj5svguevayv9vzq4c08yvj3yday2mx64quhql8vjecvqxq9rz9ql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTUpBQ3NUdno1TEp2UlIz
            dTlKTTBGVVNLTGZMUk90TUx1SlB6QnQ0bmdvCnZwVzNwc29KVEpaUDZXTlJHcEto
            dW9xZldESnVyQzM5TTFJMDJnRFZjWEkKLS0tIGI4Z05ZWlZjdkJuZFRNSFp2QWo0
            UDNFVjJORVJPQTZjbWlHVDE0ZEwxUG8KKI1d1tA/w832FKjWWDhQl2rCamtQaG5G
            YyUtHB67LFhWXir2zzhEPB+Eo78y9KoUy3gxm9EV3GuG7A9adX+Z1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T05:24:23Z"
    mac: ENC[AES256_GCM,data:xu3jgEdcnjw1arBAqSvcfGggxV2ILXkGFSzWkd7utbi1kEsr2G9BafnbGOtNvCfQ5z31hdyazksxyyCaeLAxC9xwnL0946QDJWlg60gXvfpLOO+3yVAxOuqNiTiWMOYdYzYqH05agxlw/g9at+WDh/i6dGydcM6WnftT5L5YzfY=,iv:1W7qAFhBJtvbcigdM6tAuSatTd6xHgTMYjSnQ/amxFg=,tag:VcrUVkJeZBm4XqicDrTurA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
