apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kwQjFF6KIYXJpplYow2iNRzuB3vFSU9P2AxeK3lQTAdiN3gOqgaUNw==,iv:kS+olInI173hdfAkbosTx1k4MVXBmcEhTTVm5GA+QCM=,tag:r7Ta1+C1gGOIKtuWc4Ho/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u467mxj5svguevayv9vzq4c08yvj3yday2mx64quhql8vjecvqxq9rz9ql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcmRYajFWamYrTFZ5eFRy
            aEJ4SUlTaEZwd2VPY2N4YnVhRjlkQnFNWWtNCklzT2lpUjNzemxxdkI5d0lmUVZq
            ajRONURrLzErbW1oUFNmd0pub0NzaEUKLS0tIFdIMkg0OCtqSGI1UG1uN0lVOHEx
            VExOdlQrMEt3WmdaNHhzV3FYTzdlWXMKt1jkyE5/FTREac0ez32U593nfiE6HhqK
            hw/m3z89nwB/dQbphWPpEv20DuqSMBid/hdTcnQ7myhyHCuOnNzwJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T04:36:14Z"
    mac: ENC[AES256_GCM,data:+A3kyqJGJwI66ns5jA5N1nEs0klSheGyBTCTAPmZ/GMVMn4jRgK8FK0r5WXnQ+7OWxQxkig1NvXry3oULieknxKeFAFuA3fV722MXppGEtif3O4DzVVne81Hj2zrsBv7ztOTtv46kSu2/I1QkpbRF8Eel4pM5BtPAanPmq4np4k=,iv:FtqIanyeqAU4h0jmypjazzoboyC0+16kRIrliTpUjMg=,tag:QUQsaGaoeW3CXI2Papuc2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
