---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  install:
    remediation:
      retries: 10
  values:
    fullnameOverride: nfs-subdir-external-provisioner
    nfs:
      server: "10.100.1.20"
      path: "/volume2/kubernetes"
    storageClass:
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
      defaultClass: false
      name: nfs-kube
