---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: default
spec:
  interval: 10m
  releaseName: my-docker-registry
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: latest
  values:
    expose:
      type: loadBalancer
      tls:
        enabled: false
      ingress:
        main:
          enabled: true
          ingressClassName: nginx
          annotations:
            external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hosts:
            - host: &host "registry.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "registry.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
