---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2023.5.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    fullnameOverride: authentik
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.5.2
      pullPolicy: Always
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.home.arpa/enabled: "true"
        external-dns-cf/is-dns-public: "true"
      hosts:
        - host: auth.whitelabs.tech
          paths:
            - path: /
          tls:
            - hosts:
                - auth.whitelabs.tech
    authentik:
      log_level: trace
      secret_key:
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: authentik_secret_key
      error_reporting:
        enabled: true
        environment: kryptonian
      postgresql:
        enabled: true
        host: postgres.database.svc.cluster.local
        name: authentik
        user: authentik
        password:
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: postgres_password
      redis:
        enabled: true
        host: redis.database.svc.cluster.local
      email:
        host: 10.100.1.5
        port: 25
        use_tls: false
