---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-home
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/fenrus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
