apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:/ucYtAQCMBF6P1WyFUtHqIpLA4BkdPEBNdTDrkh+IRMt0PfMye3doPW++N/6jVqSulBUbHz7OO+OPjCh,iv:OHCRtVdb4Px/9rWQ/qvU1jxR0nIpGMsnQynkg0u9Tjc=,tag:dtdpvZ/ec1x2Bjfk/dcl2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u467mxj5svguevayv9vzq4c08yvj3yday2mx64quhql8vjecvqxq9rz9ql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RlpYYkFjRjllKzJqTjEz
            c3NlVDFzRXAyL2dwMXlMZ3BQY0wxMG1FcW1zCjV6V21mTzFlWmNXUlNZWlNNRDBI
            MTNEcnRLVWVsMmlOZld0TnVZb3l2aUUKLS0tIDRjRkhCTEthS2RsNWNCeW0rWStw
            akM0KzdXSjVLYUdrMU8xNDIxSklLL3MKU3XCQTeOQWiO283qVU7g8qJp8muiaGNc
            fAX6TRJva4xBHD2QNZPiUk1fOEibeHqi8/d7KOtcjEvWfoedC93SKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T04:36:14Z"
    mac: ENC[AES256_GCM,data:mBWzzZrmh7yC1frA6uv0jwYbMg7atodwibGbElaHDuy4kqkLqhnsO4evzmgl5uunPOQfiHayzT1pN998QiIWSFQ5apJmMGoAeDS6UKgDoAYMeR8Zea5+r2xT1wJtXOt6S0KCF+ooEd88fFLL5/WN0FCGdimddxNjOgMlPdFUP3k=,iv:+pKYUughz4ONqY1h7ZyWsr7CsXdhisi94IGkiMEbbWc=,tag:voL+vWnQ3nPW00CHj+KA/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
