---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.99.100.19"
  METALLB_LB_RANGE: "10.99.100.20-10.99.100.39"
  METALLB_K8S_GATEWAY_ADDR: "10.99.100.20"
  METALLB_INGRESS_ADDR: "10.99.100.21"
