---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-v1
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-kube
  resources:
    requests:
      storage: 10Gi
