---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    auth:
      enablePostgresUser: true
      postgresPassword: ${SECRET_POSTGRES_ADMIN_PASS}
      database: postgres
    primary:
      persistence:
        enabled: true
      initdb:
        scripts:
          init-authentik.sql: |
            CREATE ROLE "authentik" WITH LOGIN PASSWORD '$SECRET_AUTHENTIK_DATABASE_PASSWORD';
            CREATE DATABASE authentik WITH OWNER 'authentik' ENCODING 'UTF8' TEMPLATE template0;
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: postgresPassword
      targetPath: auth.postgresPassword
