---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    containerSecurityContext:
      runAsUser: 0
    # diagnosticMode:
    #  enabled: true
    # auth:
    #   postgresPassword: ^valuesFrom^
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-v1
      # initdb:
      # scripts:
      # init-example1.sql: |
      # CREATE ROLE "example" WITH LOGIN PASSWORD 'example';
      # CREATE DATABASE example WITH OWNER 'example' ENCODING 'UTF8' TEMPLATE template0;
      # init-example2.sql: |
      # CREATE ROLE "example" WITH LOGIN PASSWORD 'example';
      # CREATE DATABASE example WITH OWNER 'example' ENCODING 'UTF8' TEMPLATE template0;
      resources:
        requests:
          cpu: 15m
          memory: 226M
        limits:
          memory: 226M
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: postgresPassword
      targetPath: auth.postgresPassword
