---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 6m
  chart:
    spec:
      chart: postgresql
      version: 12.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    containerSecurityContext:
      runAsUser: 0
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-v01
      initdb:
        scripts:
          init-authentik.sql: |
            CREATE ROLE "authentik" WITH LOGIN PASSWORD '$SECRET_AUTHENTIK_DATABASE_PASSWORD';
            CREATE DATABASE authentik WITH OWNER 'authentik' ENCODING 'UTF8' TEMPLATE template0;
      resources:
        requests:
          cpu: 15m
          memory: 226M
        limits:
          memory: 226M
  valuesFrom:
    - kind: Secret
      name: postgres
      valuesKey: postgresPassword
      targetPath: auth.postgresPassword
