---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresqlv1
  resources:
    requests:
      storage: 10Gi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
