---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql01
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
