apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: database
stringData:
    postgresPassword: ENC[AES256_GCM,data:A9fGk54z6h1f5K/+z+bPAjlfKh4Q7ZEijETgUFbLClsfk+usZGgXRouWaTXPoAiPbR8nJyyIm5hPnu2VZ1Vqeg==,iv:VJajkebhfS5+4eMuUN80xn+dWz3mgHAmUssTjY5+gDo=,tag:+6kHIo5EQUOt+XVeg5cTRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u467mxj5svguevayv9vzq4c08yvj3yday2mx64quhql8vjecvqxq9rz9ql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY0NyV2JVTEhCYUZlTFEz
            VzBJT3dtVzhSQUpSSmc0d1c0Qjhlanhja2s0CjBIQklFUGFQV21YYjFpdmJOUUxo
            T0E5dVRaSTlEdmIvdm9YZU94SHpOclkKLS0tIC9xdEMrWEpXNE02QmVad3FMQ1R2
            NU43Y0ZJTXRSclcxZ2lIYVFCdFR1bW8KholaqKg0fbrTB9uyeXNyUja2vN8Y1/9M
            qiXgKZsiuQJH19a+lLg+7hQJnz4fWCAFNTiUCOW5pplWYd9fdCNbqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T03:32:34Z"
    mac: ENC[AES256_GCM,data:ElSXrwG/eoLcZYcuKPi9Pz9c+Q+cxs8NB6Bbt174trMb79L9E2aF8ZGUHaa/0SAP+KGHRscJeXGKQSuz4qqqLsQ7eEtqd6Gbue60I4tz4t0mymkSe4NvYnQmx9INQFx7LbL4YlQUfqPluUb+EfWevLRhqybjV6WdVbzG49B10kQ=,iv:Wb0qvMTgqGkTzVp1W5Gd2jBTxd5oaUBy6qcskd7NfGA=,tag:kY8VLDlD08eCGrCg2A8yYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
