apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
    creationTimestamp: null
    labels:
        io.kompose.service: app
    name: app
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: app
    strategy:
        type: Recreate
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert
                kompose.version: 1.28.0 (HEAD)
            creationTimestamp: null
            labels:
                io.kompose.network/docker-default: "true"
                io.kompose.service: app
        spec:
            containers:
                - env:
                    - name: DB_MYSQL_HOST
                      value: ENC[AES256_GCM,data:msw=,iv:htG9Gk1vCTjDCBQylpkAC20boYqff9CDlOmi3YR5Uc0=,tag:+IDDFdJ0pIgb0s0k1Hiixg==,type:str]
                    - name: DB_MYSQL_NAME
                      value: ENC[AES256_GCM,data:vuJn,iv:7REogk8BrRYydPpHHg+/FLsno4lX/WNYNKbJxAf8AvM=,tag:1rukbn49RXKBpbk1iCToFw==,type:str]
                    - name: DB_MYSQL_PASSWORD
                      value: ENC[AES256_GCM,data:rleA,iv:5xNh2eD2IM73lHidn8ryzm/6C1h2MQTxeP4qbjQoZQw=,tag:sadiQ0nqSJoEl77fIge81A==,type:str]
                    - name: DB_MYSQL_PORT
                      value: ENC[AES256_GCM,data:eXJbLw==,iv:rmNaV85fEeWfmiCaAQUZh4w2DE8wbHTePlySQu25MpM=,tag:hkXfFbpmt1hoSmaPm43eMA==,type:str]
                    - name: DB_MYSQL_USER
                      value: ENC[AES256_GCM,data:pcXl,iv:UNrBs0nh2TMAXhlKwHu4/lv/oa2RxD92OTKrFoxXc1c=,tag:S0KNOmiEbDuxn2C4KOwKWg==,type:str]
                  image: jc21/nginx-proxy-manager:latest
                  name: app
                  ports:
                    - containerPort: 80
                    - containerPort: 81
                    - containerPort: 443
                  resources: {}
                  volumeMounts:
                    - mountPath: /data
                      name: app-claim0
                    - mountPath: /etc/letsencrypt
                      name: app-claim1
            restartPolicy: Always
            volumes:
                - name: app-claim0
                  persistentVolumeClaim:
                    claimName: app-claim0
                - name: app-claim1
                  persistentVolumeClaim:
                    claimName: app-claim1
status: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u467mxj5svguevayv9vzq4c08yvj3yday2mx64quhql8vjecvqxq9rz9ql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbVlhT28vZGZhRFo2Wmhz
            MldQTCt3Qm0xMUg0YnNCc2p0aVVNWFU3YVE4Cm5WWDFtMmJ4WldwenU1akRIY21a
            SVY2SDcyWjZxOVRDNEljemxyTyszVGMKLS0tIHhJemx1eSttRzZtb09yM25FZDBR
            ZWVVenFLWXBLeEs3clhhRFhKM0FxNkEKy1kcKryQn+/TaQ6c6lfWnd3pUVxnMMjS
            Bcn8+nnFppl1fRQfu+x/TYq2WsmnvSJxOWBRWc5GsTu7DINo3p1k8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T06:13:01Z"
    mac: ENC[AES256_GCM,data:820LDTbP/Nr2G0wcJrUsHi4pe0RgrBJ/hN9TKIVGlV3dO0cnlF/+6hiWfmo8693ZOt+HXOXrd0fdij+cDalPw6BgQ8fpsx7kBE7a0F4+OwoPbXgoKMGzxsXTIGsCxQ0fM2hm4Qzp01hNXEFIi5H9/NZrpKrPRv3jF3bhZJPOfG8=,iv:4O8FyvPmY2eEL3o4T/28lxf+MX3fDaEZyT9FfAc4nEY=,tag:0nUEXpsbljUrfvNdoHgNwA==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.3
