apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
    creationTimestamp: null
    labels:
        io.kompose.service: db
    name: db
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: db
    strategy:
        type: Recreate
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert
                kompose.version: 1.28.0 (HEAD)
            creationTimestamp: null
            labels:
                io.kompose.network/docker-default: "true"
                io.kompose.service: db
        spec:
            containers:
                - env:
                    - name: MYSQL_DATABASE
                      value: ENC[AES256_GCM,data:ez6I,iv:dO4C7lYm1jaHggAlwAHIR05vW9DJMBNFhAJBQBfgKUg=,tag:rKV6YW3Gfj1hc7KjJrpIvw==,type:str]
                    - name: MYSQL_PASSWORD
                      value: ENC[AES256_GCM,data:uoLf,iv:hcbcF3OUX8/Z3QsIHEGriXMFnwx9qEzzFXd8UUqzVrw=,tag:vQSskO/H6kfFLq2kVZLVLQ==,type:str]
                    - name: MYSQL_ROOT_PASSWORD
                      value: ENC[AES256_GCM,data:UKht,iv:64wkadd+1j86gUVE3BGs6gimk/yY/cykhX71oLwm5PI=,tag:TzFmeFNGKil2Sq3kchr4/w==,type:str]
                    - name: MYSQL_USER
                      value: ENC[AES256_GCM,data:Oh/i,iv:yJ7SbLYSrvxLUL2RbhAIZfRojs4QxtO4Mk/n7MZh4Jg=,tag:SYNZ5zsO7WtR5HE1wbEpsg==,type:str]
                  image: jc21/mariadb-aria:latest
                  name: db
                  resources: {}
                  volumeMounts:
                    - mountPath: /var/lib/mysql
                      name: db-claim0
            restartPolicy: Always
            volumes:
                - name: db-claim0
                  persistentVolumeClaim:
                    claimName: db-claim0
status: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u467mxj5svguevayv9vzq4c08yvj3yday2mx64quhql8vjecvqxq9rz9ql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISFVSZnJlSE8xamdBUFcw
            ckJ0Vk90UEVuTVRlVGdaLzFzOFBNZ295aTIwCnRTVStGZkcrZVlZNDR0Q3hndjl1
            Y0taa00ycnVyV3lBTGtNNFkwNGpKOGsKLS0tIGpNWW4yUDdTMDR3ZXUrVnZqd1VD
            N1IyL0JobVRUczkvRzVmNEd3c3hkWTAKgZXBb5q+7Cu5ga04meH/K5M3mMR1AJiU
            vWK2YAG0zN5kxL+tQV5N7LGrlcYPblH0DetcpwBIaDZnwwrjPzC0IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T06:16:08Z"
    mac: ENC[AES256_GCM,data:IW/0v+iVRDfgnOhYINMkY9chRybVeQ5e51AT6hDYdTvONH844++jQ6hCm4ccz4SiUGs2ubIGuJo7ABUk0LHiA3GUQUANSqG6lQIpT6aSZMz2J3jtgoKKq5oA4w9O7jX6AYbZzIhrUIdYcQBCJ72uf2eLSeucCajpHKe8hZYTvSg=,iv:sHl8rmhLPt+eTwKPJkckrf9gZc3ZLmuCFIjucmoTRFE=,tag:IyJUIRk7pkHiI/XBO8/+Zg==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.3
